datadir = get_option('datadir')

install_data(
  'io.github.idi0t.SshuttleGUI.desktop',
  install_dir: datadir / 'applications'
)

install_data(
  'io.github.idi0t.SshuttleGUI.metainfo.xml',
  install_dir: datadir / 'metainfo'
)

install_data(
  'io.github.idi0t.SshuttleGUI.policy',
  install_dir: datadir / 'polkit-1' / 'actions'
)
